issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - tagliatelle
        - dupl
        - exhaustivestruct
        - gci
        - gofumpt
        - funlen
linters:
  enable-all: true
  disable:
    - tagliatelle
    - dupl
    - exhaustivestruct
    - gci
    - gofumpt

