issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - tagliatelle
        - dupl
        - exhaustivestruct
        - gci
        - gofumpt
        - funlen
    - path: \.go
      linters:
        - tagliatelle
        - dupl
        - exhaustivestruct
        - gci
        - gofumpt
  enable-all: true

